add README, lambda_function, slacker
l-fin/LamdaCloudwatchToPrettySlack pull request #1
Opened 2019-07-04 08:49 UTC by insiderhj

[README.md]
함수에 대한 간단한 설명, 실행 방법, 실행 결과 예시 등의 정보를 이미지 (src 안의 png파일들)와 함께 담았습니다.
마지막 부분에 SNS message의 json 형식 출력의 예시를 넣어 코드를 이해하거나 수정할 때 참고할 수 있도록 했습니다.

[lambda_function.py]
맨 위에 각각의 환경 변수로서 어떠한 값을 입력받는지에 대해 주석을 추가했습니다.
함수 내에서 각 부분별로 어떠한 역할을 위한 코드인지 주석을 추가했습니다.

2019-07-04 09:01 UTC, ted-lfin requested changes

2019-07-04 09:01 UTC, dskim-lfin commented on CloudwatchToPrettySlack-179b3a84-3da5-48ba-9e69-e3ffdbe7d1ed-1 2/lambda_function.py
> +import os
폴더명이 이렇게 길어야 하나요?
CloudwatchToPrettySlack-179b3a84-3da5-48ba-9e69-e3ffdbe7d1ed-1 2

2019-07-04 09:01 UTC, dskim-lfin commented on README.md
> +json.loads(event['Records'][0]['Sns']['Message']) example
Cloudwatch alarm SNS 메시지 샘플

2019-07-05 01:48 UTC, dskim-lfin commented
개발문화 에서 gitflow 를 다시 보세요.
PR 은 이렇게 하는 겁니다.

lfin/develop <-- insiderhj/develop

2019-07-05 01:48 UTC, closed without merging